"""empty message

Revision ID: 0c1210b9d99e
Revises: 
Create Date: 2020-02-17 14:20:37.216363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1210b9d99e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    Artist=op.create_table('Artist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('seeking_venue', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(length=500), nullable=True),
    sa.Column('genres', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    Venue=op.create_table('Venue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('seeking_talent', sa.Boolean(), nullable=True),
    sa.Column('seeking_description', sa.String(length=500), nullable=True),
    sa.Column('genres', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    Show=op.create_table('Show',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.bulk_insert(Artist,
                   [
                       {'id': 4, 'name': 'The Wild Sax Band', 'city': 'San Francisco', 'state': 'CA',
                        'phone': '432-325-5432', 'seeking_venue': False, 'website' : '',
                        'genres': 'Classical',  'seeking_description' : '',
                        'image_link': 'https://images.unsplash.com/photo-1558369981-f9ca78462e61?ixlib:rb-1.2.1&ixid:eyJhcHBfaWQiOjEyMDd9&auto:format&fit:crop&w:794&q:80'},
                       {'id': 5, 'name': 'Guns N Petals', 'city': 'San Francisco', 'state': 'CA',
                        'phone': '326-123-5000',
                        'genres': '[Rock n Roll]', 'website': 'https://www.gunsnpetalsband.com',
                        'facebook_link': 'https://www.facebook.com/GunsNPetals',
                        'seeking_venue': True,
                        'seeking_description': 'Looking for shows to perform at in the San Francisco Bay Area!',
                        'image_link': 'https://images.unsplash.com/photo-1549213783-8284d0336c4f?ixlib:rb-1.2.1&ixid:eyJhcHBfaWQiOjEyMDd9&auto:format&fit:crop&w:300&q:80'},
                       {'id': 6, 'name': 'Matt Quevedo', 'city': 'New York', 'genres': 'Jazz', 'state': 'NY',
                        'phone': '300-400-5000', 'facebook_link': 'https://www.facebook.com/mattquevedo923251523',
                        'seeking_venue': False, 'website' : '', 'seeking_description' : '',
                        'image_link': 'https://images.unsplash.com/photo-1495223153807-b916f75de8c5?ixlib:rb-1.2.1&i'
                                      'xid:eyJhcHBfaWQiOjEyMDd9&auto:format&fit:crop&w:334&q:80'}
                   ]
                   )
    op.bulk_insert(Venue,
           [
               {'id': 1, 'city': 'San Francisco', 'state': 'CA', 'name': 'The Musical Hop',
                'address': '1015 Folsom Street', 'phone': '23-123-1234',
                'website': 'https://www.themusicalhop.com', 'genres': '[Classical]',
                'facebook_link': 'https://www.facebook.com/TheMusicalHop', 'seeking_talent': True,
                'seeking_description': 'We are on the lookout for a local artist to play every two weeks. Please call us.',
                'image_link': 'https://images.unsplash.com/photo-1543900694-133f37abaaa5?ixlib:rb-1.2.1&ixid:eyJhcHBfaWQiOjEyMDd9&auto:format&fit:crop&w:400&q:60'},
               {'id': 2, 'city': 'New York', 'state': 'NY', 'name': 'The Dueling Pianos Bar',
                'address': '335 Delancey Street',
                'phone': '914-003-1132',
                'website': 'https://www.theduelingpianos.com',
                'genres': '[Classical, R&B,Hip-Hop]',
                'facebook_link': 'https://www.facebook.com/theduelingpianos',
                'seeking_talent': False, 'seeking_description' : '',
                'image_link': 'https://images.unsplash.com/photo-1497032205916-ac775f0649ae?ixlib:rb-1.2.1&ixid:eyJhcHBfaWQiOjEyMDd9&auto:format&fit:crop&w:750&q:80'},
               {'id': 3, 'city': 'San Francisco', 'state': 'CA', 'name': 'Park Square Live Music & Coffee',
                'address': '34 Whiskey Moore Ave',
                'genres': '[Rock n Roll,Jazz,Classical,Folk]', 'phone': '415-000-1234',
                'website': 'https://www.parksquarelivemusicandcoffee.com',
                'facebook_link': 'https://www.facebook.com/ParkSquareLiveMusicAndCoffee',
                'seeking_talent': False, 'seeking_description' : '',
                'image_link': 'https://images.unsplash.com/photo-1485686531765-ba63b07845a7?ixlib:rb-1.2.1&ixid:eyJhcHBfaWQiOjEyMDd9&auto:format&fit:crop&w:747&q:80'}
           ]
    )
    # ### end Alembic commands ###
    op.bulk_insert(Show,
                   [
                       {'id': 1, 'venue_id': 1, 'artist_id': 4, 'start_time': '2019-05-21T21:30:00.000Z'},
                       {'id': 2, 'venue_id': 3, 'artist_id': 5, 'start_time': '2019-06-15T23:00:00.000Z'},
                       {'id': 3, 'venue_id': 3, 'artist_id': 6, 'start_time': '2035-04-01T20:00:00.000Z'},
                       {'id': 4, 'venue_id': 3, 'artist_id': 6, 'start_time': '2035-04-08T20:00:00.000Z'},
                       {'id': 5, 'venue_id': 3, 'artist_id': 6, 'start_time': '2035-04-15T20:00:00.000Z'}
                   ]
                   )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Show')
    op.drop_table('Venue')
    op.drop_table('Artist')
    # ### end Alembic commands ###
